export const uavPickerOptions = [
  { key: 'DJI Mavic Air', brand: 'dji' },
  { key: 'DJI Spark', brand: 'dji' },
  { key: 'DJI Mavic Air2', brand: 'dji' },
  { key: 'DJI Mavic Pro', brand: 'dji' },
  { key: 'DJI Mavic Pro2', brand: 'dji' },
  { key: 'DJI Mavic 2 ZOOM', brand: 'dji' },
  { key: 'DJI Mavic Mini', brand: 'dji' },
  { key: 'DJI Mavic Mini2', brand: 'dji' },
  { key: 'DJI Phantom', brand: 'dji' },
  { key: 'DJI Phantom 3', brand: 'dji' },
  { key: 'DJI Phantom 4', brand: 'dji' },
  { key: 'DJI Phantom 4 Pro', brand: 'dji' },
  { key: 'DJI Phantom 3 SE', brand: 'dji' },
  { key: 'DJI Inspire 1', brand: 'dji' },
  { key: 'DJI Inspire 2', brand: 'dji' },
  { key: 'DJI Matrice 100', brand: 'dji' },
  { key: 'DJI MATRICE 300 RTK', brand: 'dji' },
  { key: 'DJI Matrice 200 Series', brand: 'dji' },
  { key: 'DJI Matrice 600', brand: 'dji' },
  { key: 'Syma X30', brand: 'syma' },
  { key: 'Syma W1 PRO', brand: 'syma' },
  { key: 'Syma X25 PRO', brand: 'syma' },
  { key: 'Syma X8 PRO', brand: 'syma' },
  { key: 'Syma X27', brand: 'syma' },
  { key: 'Syma X20P', brand: 'syma' },
  { key: 'Syma X22SW', brand: 'syma' },
  { key: 'Syma X15A', brand: 'syma' },
  { key: 'Syma X20W', brand: 'syma' },
  { key: 'Syma X26', brand: 'syma' },
  { key: 'Syma X22W', brand: 'syma' },
  { key: 'Syma X5HW', brand: 'syma' },
  { key: 'Syma X8HW', brand: 'syma' },
  { key: 'Syma X5UW', brand: 'syma' },
  { key: 'Syma X5SW', brand: 'syma' },
  { key: 'Syma Z1', brand: 'syma' },
  { key: 'Syma Z3', brand: 'syma' },
  { key: 'Hubsan Zino Pro', brand: 'hubsan' },
  { key: 'Hubsan F22', brand: 'hubsan' },
  { key: 'Hubsan Zino', brand: 'hubsan' },
  { key: 'Hubsan H216A', brand: 'hubsan' },
  { key: 'Hubsan H501M', brand: 'hubsan' },
  { key: 'Hubsan H501A', brand: 'hubsan' },
  { key: 'Hubsan H507A+', brand: 'hubsan' },
  { key: 'Hubsan H502S', brand: 'hubsan' },
  { key: 'Hubsan H501S', brand: 'hubsan' },
  { key: 'Hubsan H109S', brand: 'hubsan' },
  { key: 'Hubsan H107D+', brand: 'hubsan' },
  { key: 'Hubsan H107D', brand: 'hubsan' },
  { key: 'Hubsan H109', brand: 'hubsan' },
  { key: 'Hubsan H502T', brand: 'hubsan' },
  { key: 'Hubsan H502E', brand: 'hubsan' },
  { key: 'Hubsan H123D', brand: 'hubsan' },
  { key: 'Hubsan H107D+', brand: 'hubsan' },
];
